config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  scope :home do
    get 'about' => 'homes#about'
  end

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  get 'search' => 'search#search'

  resources :groups, only: [:index, :new, :create, :show, :edit, :update] do
    resources :group_users, only: [:create, :destroy]
    resources :group_messages, only: [:new, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  # UserモデルとN対1の関係にある（複数の本が、1人のユーザーと紐づいている）
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum:200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search_type, keyword)
    if search_type == "perfect"
      Book.where(title: keyword)
    elsif search_type == "forward"
      Book.where("title LIKE ?", "#{keyword}%" )
    elsif search_type == "rear"
      Book.where("title LIKE ?", "%#{keyword}" )
    elsif search_type == "partial"
      Book.where("title LIKE ?", "%#{keyword}%" )
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :group_messages, dependent: :destroy

  attachment :image

  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  
end

app/models/group_message.rb
class GroupMessage < ApplicationRecord
  
belongs_to :group

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :followed_id, presence: true
  validates :followed_id, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # bookモデルと1対N（ユーザー1人に対して複数の本が紐づいている。）dependent: :destroyで、ユーザーが消えたら紐づいた本も消える
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  attachment :profile_image

  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 50 }
  validates :introduction, length: { maximum: 50 }

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def self.search(search_type, keyword)
    if search_type == "perfect"
      User.where(name: keyword)
    elsif search_type == "forward"
      User.where("name LIKE ?", "#{keyword}%" )
    elsif search_type == "rear"
      User.where("name LIKE ?", "%#{keyword}" )
    elsif search_type == "partial"
      User.where("name LIKE ?", "%#{keyword}%" )
    end
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # newはviewファイル必要ないので作らない。
  # 本の一覧
  def index
    @books = Book.page(params[:page]).reverse_order
    @book = Book.new
    @user = current_user
  end

  # 新しい本をデータベースに追加
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end

  end

  #本の詳細画面
  def show
    @new_book = Book.new
    @book = Book.find(params[:id]).reverse_order
    @user = @book.user
    @book_comment = BookComment.new
  end

  #本の更新画面
  def edit
    @book = Book.find(params[:id])
    redirect_to books_path unless current_user.id == @book.user_id
  end

  #本の内容の変更をデータベースに更新
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  #本のデータを削除
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body, :image)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.page(params[:page]).reverse_order
    @book = Book.new
    @user = current_user
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
    @book = Book.new
    @user = current_user
    @users = @group.users.page(params[:page]).reverse_order
  end
  
  def create
    @user = current_user
    @group = @user.groups.build(group_params)
    @group.owner_id = @user.id
    @user.save
    redirect_to groups_path

  end

  def edit
    @group = Group.find(params[:id])
    redirect_to groups_path unless current_user.id == @group.owner_id
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to groups_path
  end


  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image, { user_ids: []})
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # user一覧画面
  def index
    @user = current_user
    @users = User.page(params[:page])
    @book = Book.new
  end

  # userの詳細
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
  end

  # user情報の更新画面
  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless current_user.id == @user.id    
  end

  # userの情報をデータベースに更新
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  def following
    @user = User.find(params[:id])
    @users = @user.following.all
    render 'show_following'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.all
    render 'show_follower'
  end
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_list.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user.id)do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50' %>
        <% end %>
      </td>
      <td><%=link_to book_path(book) do %><%= book.title %><% end %></td>
      <td><%= book.body %></td>
      <% unless controller.action_name == "show" %>
        <td class="favorite-<%= book.id %>">
          <%= render "favorites/favorite", book: book %>
        </td>
        <td>コメント数 : <%= book.book_comments.count %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
  <%= paginate books %>

app/views/books/_book_lists.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user.id)do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50' %>
        <% end %>
      </td>
      <td><%=link_to book_path(book) do %><%= book.title %><% end %></td>
      <td><%= book.body %></td>
      <% unless controller.action_name == "show" %>
        <td class="favorite-<%= book.id %>">
          <%= render "favorites/favorite", book: book %>
        </td>
        <td>コメント数 : <%= book.book_comments.count %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Title', class: "book_title" %>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>
  <div class="form-group">
    <%= f.label :body, 'Opinion', class: "book_opinion" %>
　    <%= f.text_area :body, class: "form-control book_opinion" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1 class="edit-heading">Editing Book</h1>
        <%= render "layouts/errors", object: @book %>
        <%= render "books/form", book: @book %>
      <div class="show-back">
        <%= link_to "Show", book_path(@book) %>
          |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render "layouts/errors", object: @book %>
  <div class="row">
    <div class="col-md-3">
    <%= render "users/user_info", user: @user %>
    <h2 class="mt-3">New book</h2>
    <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render "books/book_list", books: @books %>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= render "users/user_info", user: @user %>
    <h2 class="mt-3">New book</h2>
    <%= render "books/form", book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2 class="detail-heading">Book detail</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="5"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50' %><br/>
                <%= @user.name %>
              <% end %>
            </td>
            <td><%=link_to book_path(@book) do %><%= @book.title %><% end %></td>
            <td><%= @book.body %></td>
            <td class="favorite-<%= @book.id %>">
              <%= render "favorites/favorite", book: @book %>
            </td>
            <td>
              コメント数 : <%= @book.book_comments.count %>
            </td>
            <% if @user.id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success btn-sm" %></td>
              <td><%= link_to "Destroy", book_path(@book), class:"btn btn-danger btn-sm", method: :delete, data: {confirm: "本当に消しますか？"} %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div class="comments">
        <table class="comment-<%= @book.id %>">
          <%= render "book_comments/comment_list", {book: @book} %>
        </table>
        <div classs="comment-form">
          <%= render "book_comments/comment_form", {book: @book, book_comment: @book_comment} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/_group_list.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% groups.each do |group| %>
    <tr>
      <td>
        <%= attachment_image_tag group, :image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50' %>
      </td>
      <td><%=link_to group_path(group) do %><%= group.name %><% end %></td>
      <td><%= group.introduction %></td>
      <% if group.owner_id == current_user.id %>
        <td>
          <%= link_to "Edit", edit_group_path(group), class:"btn btn-success btn-sm" %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate groups %>

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px px-sm-0 mx-auto">
      <h2>Editing Group</h2>
      <%= render "layouts/errors", object: @group %>
      <%= form_with model:@group, local:true do |f| %>
        <div class="form-group">
          <%= f.label :name, 'グループ名', class: "group_name" %>
          <%= f.text_field :name, class: "edit-user-text form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, 'Introduction', class: "group_introduction" %>
          <%= f.text_area :introduction, class: "edit-user-text form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :image, 'グループ画像', class: "inputImage" %>
          <%= f.attachment_field :image, class: "form-control-file profile_image" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Group', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render "layouts/errors", object: @book %>
  <div class="row">
    <div class="col-md-3">
    <%= render "users/user_info", user: @user %>
    <h2 class="mt-3">New book</h2>
    <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <%= link_to "グループを作成する", new_group_path %>
        |
      <%= link_to "グループ一覧", groups_path %>      
      <%= render "groups/group_list", groups: @groups %>
    </div>

  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px px-sm-0 mx-auto">
      <h2>Create Group</h2>
      <%= render "layouts/errors", object: @group %>
      <%= form_with model:@group, local:true do |f| %>
        <div class="form-group">
          <%= f.label :name, 'グループ名', class: "group_name" %>
          <%= f.text_field :name, class: "edit-user-text form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, 'Introduction', class: "group_introduction" %>
          <%= f.text_area :introduction, class: "edit-user-text form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :image, 'グループ画像', class: "inputImage" %>
          <%= f.attachment_field :image, class: "form-control-file profile_image" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Group', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container px-5 px-sm-0">
  <%= render "layouts/errors", object: @book %>
  <div class="row">
    <div class="col-md-3">
    <%= render "users/user_info", user: @user %>
    <h2 class="mt-3">New book</h2>
    <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Group detail</h2>
      <%= link_to "グループを作成する", new_group_path %>
        |
      <%= link_to "グループ一覧", groups_path %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag @group, :image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50' %>
            </td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.users.each do |user| %>
                <%= user.name %><br/>
              <% end %>
            </td>
              <% if current_user.id != @group.owner_id && !@group.users.include?(current_user) %>
                <td>
                  <%= link_to "Join this group", group_group_users_path(@group), class: "btn btn-success btn-sm", method: :post %>
                </td>
              <% elsif current_user.id != @group.owner_id && @group.users.include?(current_user) %>
                <td>
                  <%= link_to "Leave this group", group_group_user_path(@group), class: "btn btn-danger btn-sm", method: :delete %>
                </td>
              <% elsif current_user.id == @group.owner_id %>
                <td>
                  <%= link_to "Edit", edit_group_path(@group), class:"btn btn-success btn-sm" %>
                </td>
                <td>
                  <%= link_to "Notice an Event", new_group_group_message_path(@group), class: "btn btn-info btn-sm" %>
                </td>
              <% end %>
          </tr>
        </tbody>
      </table>


    </div>

  </div>
</div>

app/views/users/_user_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'100x100' %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th>
        <a href="<%= following_user_path(user) %>">
          <%= user.following.count %>
        </a>
      </th>
    </tr>
    <tr>
      <th>followers</th>
      <th>
        <a href="<%= followers_user_path(user) %>">
          <%= user.followers.count %>
        </a>
      </th>
    </tr>
  </tbody>
</table>
<div class="row">
  <% if user == current_user %>
    <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block fas fa-user-cog " do %><% end %>
  <% else %>
    <div id="follow_form">
    <% if current_user.following?(user) %>
      <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), html: { method: :delete }, local: true) do |f| %>
        <%= f.submit "フォロー外す", class: "btn btn-info" %>
      <% end %>
    <% else %>
      <%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
        <div><%= hidden_field_tag :followed_id, user.id %></div>
        <%= f.submit "フォローする", class: "btn btn-success" %>
      <% end %>
    <% end %>
    </div>
  <% end %>
</div>

app/views/users/_user_list.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
    <tr>
      <td>
        <%= link_to user_path(user) do %>
          <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50' %>
        <% end %>
        </td>
      <td><%= user.name %></td>
      <td>フォロー数: <%= user.following.count %></td>
      <td>フォロワー数: <%= user.followers.count %></td>
      <% if user == current_user %>
        <td></td>
      <% else %>
        <td>
          <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), method: :delete %>
          <% else %>
          <%= link_to "フォローする", relationships_path(followed_id: user.id), method: :post%>
          <% end %>
        </td>
      <% end %>
      <td><%= link_to "Show", user_path(user) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate users %>

app/views/users/_user_lists.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
    <tr>
      <td>
        <%= link_to user_path(user) do %>
          <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50' %>
        <% end %>
        </td>
      <td><%= user.name %></td>
      <td>フォロー数: <%= user.following.count %></td>
      <td>フォロワー数: <%= user.followers.count %></td>
      <% if user == current_user %>
        <td></td>
      <% else %>
        <td>
          <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), method: :delete %>
          <% else %>
          <%= link_to "フォローする", relationships_path(followed_id: user.id), method: :post%>
          <% end %>
        </td>
      <% end %>
      <td><%= link_to "Show", user_path(user) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render "layouts/errors", object: @user %>
      <%= form_with model:@user, local:true do |f| %>
        <div class="edit-contents form-group">
          <%= f.label :name, 'Name', class: "user_name" %>
          <%= f.text_field :name, class: "edit-user-text form-control" %>
        </div>
        <div class="edit-contents form-group">
          <%= f.label :profile_image, 'Image', class: "inputImage" %>
          <%= f.attachment_field :profile_image, class: "form-control-file profile_image" %>
        </div>
        <div class="edit-contents form-group">
          <%= f.label :introduction, 'Introduction', class: "user_profile" %>
          <%= f.text_area :introduction, class: "edit-user-text form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render "layouts/errors", object: @book %>
  <div class="row">
    <div class="col-md-3">
    <%= render "users/user_info", user: @user %>
    <h2 class="mt-3">New book</h2>
    <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %>
        |
      <%= link_to "グループ一覧", groups_path %>

      <%= render "users/user_list", users: @users %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= render "users/user_info", user: @user %>
    <h2 class="mt-3">New book</h2>
    <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render "books/book_list", books: @books %>
    </div>
  </div>
</div>

app/views/users/show_follower.html.erb
<h2>Follower Users</h2>
<% if @user.followers.count == 0 %>
  <p>ユーザーはいません</p>
<% else %> 
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50' %>
          <% end %>
          </td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.following.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/show_following.html.erb
<h2>Follow Users</h2>
<% if @user.following.count == 0 %>
  <p>ユーザーはいません</p>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50' %>
          <% end %>
          </td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.following.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>