config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  scope :home do
    get 'about' => 'homes#about'
  end

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  get 'search' => 'search#search'

  resources :groups, only: [:index, :new, :create, :show, :edit, :update] do
    resources :group_users, only: [:create, :destroy]
    resources :group_messages, only: [:new, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  # UserモデルとN対1の関係にある（複数の本が、1人のユーザーと紐づいている）
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum:200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search_type, keyword)
    if search_type == "perfect"
      Book.where(title: keyword)
    elsif search_type == "forward"
      Book.where("title LIKE ?", "#{keyword}%" )
    elsif search_type == "rear"
      Book.where("title LIKE ?", "%#{keyword}" )
    elsif search_type == "partial"
      Book.where("title LIKE ?", "%#{keyword}%" )
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :group_messages, dependent: :destroy

  attachment :image

  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  
end

app/models/group_message.rb
class GroupMessage < ApplicationRecord
  
belongs_to :group

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :followed_id, presence: true
  validates :followed_id, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # bookモデルと1対N（ユーザー1人に対して複数の本が紐づいている。）dependent: :destroyで、ユーザーが消えたら紐づいた本も消える
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  attachment :profile_image

  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 50 }
  validates :introduction, length: { maximum: 50 }

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def self.search(search_type, keyword)
    if search_type == "perfect"
      User.where(name: keyword)
    elsif search_type == "forward"
      User.where("name LIKE ?", "#{keyword}%" )
    elsif search_type == "rear"
      User.where("name LIKE ?", "%#{keyword}" )
    elsif search_type == "partial"
      User.where("name LIKE ?", "%#{keyword}%" )
    end
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # newはviewファイル必要ないので作らない。
  # 本の一覧
  def index
    @books = Book.page(params[:page]).reverse_order
    @book = Book.new
    @user = current_user
  end

  # 新しい本をデータベースに追加
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end

  end

  #本の詳細画面
  def show
    @new_book = Book.new
    @book = Book.find(params[:id]).reverse_order
    @user = @book.user
    @book_comment = BookComment.new
  end

  #本の更新画面
  def edit
    @book = Book.find(params[:id])
    redirect_to books_path unless current_user.id == @book.user_id
  end

  #本の内容の変更をデータベースに更新
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  #本のデータを削除
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body, :image)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # user一覧画面
  def index
    @user = current_user
    @users = User.page(params[:page])
    @book = Book.new
  end

  # userの詳細
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
  end

  # user情報の更新画面
  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless current_user.id == @user.id    
  end

  # userの情報をデータベースに更新
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  def following
    @user = User.find(params[:id])
    @users = @user.following.all
    render 'show_following'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.all
    render 'show_follower'
  end
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<div class="error-messages">
  <h3><%= pluralize(object.errors.count, "error") %> prohibited this obj from being saved:</h3>
  <ul>
      <% object.errors.full_messages.each do |message| %>
        <li>
            <%= message %>
        </li>
      <% end %>
  </ul>
  
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
	  <div class="row">
		  <div class="mx-auto">
			  <p>CopyRight Infratop.inc</p>
		  </div>
	  </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-1">
		<div class="container">
			<%= link_to "Bookers",  root_path, class: 'navbar-brand' %>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expand="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNavDropdown">
				<ul class="navbar-nav ml-auto">
					<% if user_signed_in? %>
					<li>
						<%= link_to " Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
					</li>
					<li>
						<%= link_to " Users", users_path, class: 'fas fa-users nav-link text-light' %>
					<li>
						<%= link_to "Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
					</li>
					<li>
						<%= link_to " logout", destroy_user_session_path, class: 'fas fa-sign-out-alt nav-link text-light', method: :delete %>
					</li>
					<% else %>
					<li>
						<%= link_to " Home", root_path, class: 'nav-link text-light fas fa-home' %>
					</li>
					<li>
						<%= link_to " About", about_path, class: 'nav-link text-light fas fa-link' %>
					</li>
					<li>
						<%= link_to " sign up", new_user_registration_path, class: 'nav-link text-light fas fa-user-plus' %>
					</li>
					<li>
						<%= link_to " login", new_user_session_path, class: 'nav-link text-light fas fa-sign-in-alt' %>
					</li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>
	<% if user_signed_in? %>
		<div class="search-form text-center">
			<%= form_with url: search_path, method: :get, local: true do |f| %>
				<%= f.text_field :keyword %>
				<%= f.select :table, [["User", "user_table"], ["Book", "book_table"]] %>
				<%= f.select :search_type, [["完全一致", "perfect"], ["前方一致", "forward"], ["後方一致", "rear"], ["部分一致", "partial"]] %>
				<%= f.submit " 検索\ " %>
			<% end %>
		</div>
	<% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<%= render "layouts/header" %>

    <main>
  		<p id="notice"><%= flash[:notice] %></p>

      <%= yield %>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>